### ISSUE TITLE
A problem about full screen

### ISSUE THREAD

**Issue by st127** [hzcx998/xbook2#10]
So fast! I am happy to see a new gui
There are three buttons In the upper left corner of each window,I clicked each one
But it seems that the application "bosh" cannot be full screen,when I click the button,desktop seems to be crashed
Should we add a new argument to g_new_window() ? Let us call it flags.Application can use it to tell the OS if it supports full screen.

**Comment by hzcx998** [comment]
Yes, those functions are definitely needed, but they have not been done yet. Moreover, the style of the window can be adjusted later, which is equivalent to the kind of skin. At present, only the most basic thing is taken out, and it will be improved later.

**Comment by st127** [comment]
I get it.
I hope everything goes well :)
