### ISSUE TITLE
在执行命令make qemudbg时系统出错

### ISSUE THREAD

**Issue by kksh3ll** [hzcx998/xbook2#17]
gcc 版本 9.2.1 20200130 (Arch Linux 9.2.1+20200130-2) 
NASM version 2.15.05
qemu-i386 version 4.2.0

执行make qemudbg命令时，虚拟机屏幕显示：Guest has not initialized the display (yet).
截取部分log如下：

/root/usr/socket_server  size=36648
/root/usr/tests  size=97644
/root/usr/bosh  size=83956
/root/usr/freeterm  size=80904
/root/usr/lv  size=876180
/root/usr/c4  size=46376
[fs]: init done.
video info: w:1024 h:768 bpp:16 
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!                    
intr_general_handler: touch TRIGHW trigger because a expection 6 occur!

**Comment by hzcx998** [comment]
感谢您的反馈！等我们修复后再回复您！

**Comment by hzcx998** [comment]
目前不能解决该问题，请用其它调试方式！谢谢！
