### ISSUE TITLE
So, the kernel do not support SMP now,right?   :-)

### ISSUE THREAD

**Issue by NightfallDM** [hzcx998/xbook2#9]
Maybe add the MultiProcessor support for xbook2 is feasible, but i find it's also difficult,because should conversion the "pic" to "apic" contain the interrupt.And also will influence the process and switch  :-)                                                                                            
There May be more problems

**Comment by hzcx998** [comment]
I have also learned about SMP before, and I also know that APIC support is required. Therefore, I tried to implement APIC, but it was too complicated, involving many registers and many operations. And this is only the interrupt part, SMP also needs to use other more operations. Especially scheduling processes to different processors, synchronization and mutual exclusion issues, memory management issues. This is indeed a very complicated part.

**Comment by NightfallDM** [comment]
I quite agree with you, haha. When I thought how to add this feature into xbook2,I felt there are too (much) things to do just like to rebuild the kernel at the beginning time.  XD

**Comment by hzcx998** [comment]
Yes, there is such a big difference between supporting a single processor and multiple processors. It's too difficult to do, the new system, you can call him xbook-smp, haha.

**Comment by NightfallDM** [comment]
O(∩_∩)O good idea haha

**Comment by hzcx998** [comment]
As long as the modification of the processor is involved, it is equivalent to porting to another platform. Even x86->x86 smp.

**Comment by NightfallDM** [comment]
...emm yeah, That's also a big question.
